# Generated by Django 5.0 on 2025-10-21 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_academic_year_course_department_id_and_more'),
        ('users', '0002_user_email_verification_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email enabled')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='push enabled')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='in-app enabled')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='immediate', max_length=20, verbose_name='digest frequency')),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Array of event types to subscribe to', verbose_name='event types')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_public', models.BooleanField(default=False, help_text='Whether other instructors can use this template', verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'canned response',
                'verbose_name_plural': 'canned responses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('criteria', models.JSONField(help_text='Array of criteria with name, description, and levels', verbose_name='criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rubric',
                'verbose_name_plural': 'rubrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('resource_type', models.CharField(max_length=50, verbose_name='resource type')),
                ('resource_id', models.UUIDField(verbose_name='resource ID')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='old value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='new value')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('event_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('lecture', 'Lecture'), ('office_hours', 'Office Hours'), ('exam', 'Exam'), ('other', 'Other')], max_length=50, verbose_name='event type')),
                ('related_id', models.UUIDField(blank=True, help_text='ID of related assignment or quiz', null=True, verbose_name='related ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('recurrence_rule', models.CharField(blank=True, help_text='iCal RRULE format', max_length=255, verbose_name='recurrence rule')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendar event',
                'verbose_name_plural': 'calendar events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['course', 'start_time'], name='core_calend_course__b6c55b_idx'), models.Index(fields=['event_type'], name='core_calend_event_t_47622a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('module', 'Module')], max_length=50, verbose_name='resource type')),
                ('resource_id', models.UUIDField(verbose_name='resource ID')),
                ('version_number', models.IntegerField(verbose_name='version number')),
                ('content_snapshot', models.JSONField(verbose_name='content snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content version',
                'verbose_name_plural': 'content versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id', '-version_number'], name='core_conten_resourc_c07449_idx')],
                'unique_together': {('resource_type', 'resource_id', 'version_number')},
            },
        ),
    ]
