# Generated by Django 5.0 on 2025-10-17 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='comment')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='attachments')),
                ('is_draft', models.BooleanField(default=False, verbose_name='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'submission comment',
                'verbose_name_plural': 'submission comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='submissions/', verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes', verbose_name='file size')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='file type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'submission file',
                'verbose_name_plural': 'submission files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20, verbose_name='status')),
                ('text_answer', models.TextField(blank=True, verbose_name='text answer')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='files')),
                ('submission_url', models.URLField(blank=True, null=True, verbose_name='submission URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='grade')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('rubric_evaluation', models.JSONField(blank=True, default=dict, verbose_name='rubric evaluation')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_late', models.BooleanField(default=False, verbose_name='late submission')),
                ('days_late', models.IntegerField(default=0, verbose_name='days late')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignment')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
