import React from 'react';
import {
  Bars3Icon,
  CodeBracketSquareIcon,
  TableCellsIcon,
  PhotoIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  AcademicCapIcon,
  LightBulbIcon,
  ListBulletIcon,
  NumberedListIcon,
  CheckCircleIcon,
  ChatBubbleBottomCenterTextIcon,
  CalculatorIcon,
  PresentationChartLineIcon,
  BookOpenIcon,
  HashtagIcon,
  BeakerIcon,
  PlayCircleIcon,
  DocumentIcon,
  DocumentTextIcon,
  CubeTransparentIcon,
} from '@heroicons/react/24/outline';

const ICON_CLASS = 'h-5 w-5';

export const SLASH_COMMAND_ICONS: Record<string, React.ReactNode> = {
  paragraph: <Bars3Icon className={ICON_CLASS} />,
  heading1: <span className="text-xs font-bold">H1</span>,
  heading2: <span className="text-xs font-bold">H2</span>,
  heading3: <span className="text-xs font-bold">H3</span>,
  bulletList: <ListBulletIcon className={ICON_CLASS} />,
  orderedList: <NumberedListIcon className={ICON_CLASS} />,
  taskList: <CheckCircleIcon className={ICON_CLASS} />,
  quote: <ChatBubbleBottomCenterTextIcon className={ICON_CLASS} />,
  codeBlock: <CodeBracketSquareIcon className={ICON_CLASS} />,
  mathInline: <CalculatorIcon className={ICON_CLASS} />,
  mathBlock: <CalculatorIcon className={ICON_CLASS} />,
  table: <TableCellsIcon className={ICON_CLASS} />,
  image: <PhotoIcon className={ICON_CLASS} />,
  calloutInfo: <InformationCircleIcon className={ICON_CLASS} />,
  calloutWarn: <ExclamationTriangleIcon className={ICON_CLASS} />,
  calloutExample: <AcademicCapIcon className={ICON_CLASS} />,
  calloutHint: <LightBulbIcon className={ICON_CLASS} />,
  citation: <BookOpenIcon className={ICON_CLASS} />,
  footnote: <DocumentTextIcon className={ICON_CLASS} />,
  numberedParagraph: <HashtagIcon className={ICON_CLASS} />,
  testCase: <BeakerIcon className={ICON_CLASS} />,
  youtube: <PlayCircleIcon className={ICON_CLASS} />,
  pdf: <DocumentIcon className={ICON_CLASS} />,
  mermaid: <PresentationChartLineIcon className={ICON_CLASS} />,
  interactiveWidget: <CubeTransparentIcon className={ICON_CLASS} />,
};
