# Generated by Django 5.0 on 2025-10-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_gradebook_options_alter_questionbank_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradebook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='course',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='user',
        ),
    ]
