# Generated by Django 5.0 on 2025-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assignment_category_assignment_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description_format',
            field=models.CharField(choices=[('PLAIN', 'Plain Text'), ('MARKDOWN', 'Markdown'), ('HTML', 'HTML'), ('RICH', 'Rich Text (with LaTeX & Code)')], default='MARKDOWN', help_text='Format type for description', max_length=20, verbose_name='description format'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions_format',
            field=models.CharField(choices=[('PLAIN', 'Plain Text'), ('MARKDOWN', 'Markdown'), ('HTML', 'HTML'), ('RICH', 'Rich Text (with LaTeX & Code)')], default='MARKDOWN', help_text='Format type for instructions', max_length=20, verbose_name='instructions format'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='Reference materials, sample files, etc.', verbose_name='resources'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Reference solution (instructor only)', verbose_name='solution code'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Initial code template for students', verbose_name='starter code'),
        ),
    ]
