# Generated by Django 5.0 on 2025-10-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assignment_description_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Estimated time to complete in minutes', null=True, verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived assignments are hidden from students', verbose_name='is archived'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark as template for reuse', verbose_name='is template'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='original_assignment',
            field=models.ForeignKey(blank=True, help_text='Original assignment if this is a copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='assessments.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Assignments that must be completed before this one', related_name='unlocks', to='assessments.assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization (e.g., ["homework", "lab", "project"])', verbose_name='tags'),
        ),
    ]
