# Generated by Django 5.0 on 2025-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_add_assignment_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='browser_fingerprint',
            field=models.CharField(blank=True, max_length=255, verbose_name='browser fingerprint'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='proctoring_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='proctoring data'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCHING', 'Matching'), ('NUMERICAL', 'Numerical'), ('FORMULA', 'Formula'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay'), ('CODE', 'Code Question'), ('FILE_UPLOAD', 'File Upload Question'), ('ORDERING', 'Ordering Question'), ('HOTSPOT', 'Hotspot (Image Selection)'), ('DRAG_DROP', 'Drag and Drop')], max_length=30, verbose_name='question type'),
        ),
    ]
