# Generated by Django 5.1.13 on 2025-10-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_quizquestion_quiz'),
        ('courses', '0003_course_academic_year_course_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='courses.course'),
        ),
    ]
