# Generated by Django 5.0 on 2025-10-17 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_DUE_SOON', 'Assignment Due Soon'), ('ASSIGNMENT_GRADED', 'Assignment Graded'), ('QUIZ_AVAILABLE', 'Quiz Available'), ('QUIZ_GRADED', 'Quiz Graded'), ('COURSE_ANNOUNCEMENT', 'Course Announcement'), ('COURSE_ENROLLED', 'Course Enrolled'), ('SUBMISSION_COMMENT', 'Submission Comment'), ('GRADE_UPDATED', 'Grade Updated'), ('SYSTEM', 'System Notification')], max_length=50, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('sent_email', models.BooleanField(default=False, verbose_name='sent via email')),
                ('sent_push', models.BooleanField(default=False, verbose_name='sent via push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_assignment_created', models.BooleanField(default=True, verbose_name='email: assignment created')),
                ('email_assignment_due_soon', models.BooleanField(default=True, verbose_name='email: assignment due soon')),
                ('email_assignment_graded', models.BooleanField(default=True, verbose_name='email: assignment graded')),
                ('email_quiz_available', models.BooleanField(default=True, verbose_name='email: quiz available')),
                ('email_quiz_graded', models.BooleanField(default=True, verbose_name='email: quiz graded')),
                ('email_announcements', models.BooleanField(default=True, verbose_name='email: announcements')),
                ('app_assignment_created', models.BooleanField(default=True, verbose_name='app: assignment created')),
                ('app_assignment_due_soon', models.BooleanField(default=True, verbose_name='app: assignment due soon')),
                ('app_assignment_graded', models.BooleanField(default=True, verbose_name='app: assignment graded')),
                ('app_quiz_available', models.BooleanField(default=True, verbose_name='app: quiz available')),
                ('app_quiz_graded', models.BooleanField(default=True, verbose_name='app: quiz graded')),
                ('app_announcements', models.BooleanField(default=True, verbose_name='app: announcements')),
                ('daily_digest', models.BooleanField(default=False, verbose_name='daily digest')),
                ('weekly_digest', models.BooleanField(default=False, verbose_name='weekly digest')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
