# Generated by Django 5.0 on 2025-10-17 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('max_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='max points')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='available from')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='available until')),
                ('rubric', models.JSONField(blank=True, default=dict, help_text='Grading criteria', verbose_name='rubric')),
                ('allow_late_submission', models.BooleanField(default=False, verbose_name='allow late submission')),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0, help_text='Penalty percentage per day late', max_digits=5, verbose_name='late penalty percent')),
                ('submission_types', models.JSONField(default=list, help_text='Allowed submission types: file, text, url', verbose_name='submission types')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='aggregated score')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='breakdown')),
                ('letter_grade', models.CharField(blank=True, max_length=5, verbose_name='letter grade')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
            ],
            options={
                'verbose_name': 'gradebook entry',
                'verbose_name_plural': 'gradebook',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCHING', 'Matching'), ('NUMERICAL', 'Numerical'), ('FORMULA', 'Formula'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay')], max_length=30, verbose_name='question type')),
                ('stem', models.TextField(help_text='The main question text', verbose_name='question stem')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='options')),
                ('correct_answer', models.JSONField(blank=True, default=dict, verbose_name='correct answer')),
                ('explanation', models.TextField(blank=True, verbose_name='explanation')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='points')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'question bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True, verbose_name='time limit (minutes)')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='max attempts')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='shuffle questions')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='shuffle answers')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='show correct answers')),
                ('show_correct_answers_date', models.DateTimeField(blank=True, null=True, verbose_name='show correct answers date')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='available from')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='available until')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(verbose_name='attempt number')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='answers')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='auto score')),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='manual score')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='final score')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'quiz attempt',
                'verbose_name_plural': 'quiz attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override default question points', max_digits=6, null=True, verbose_name='points override')),
            ],
            options={
                'ordering': ['quiz', 'position'],
            },
        ),
    ]
