# Generated by Django 5.0 on 2025-10-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='courses.course'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='courses.course'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionbank'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='assessments.QuizQuestion', to='assessments.questionbank'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'due_date'], name='assessments_course__49d374_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_published'], name='assessments_is_publ_f83c27_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['course', 'user'], name='assessments_course__e4e62c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradebook',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', 'question_type'], name='assessments_course__d617aa_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_active'], name='assessments_is_acti_5cd00b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user'], name='assessments_quiz_id_6c0e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='assessments_status_ddb9e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_published'], name='assessments_course__aae811_idx'),
        ),
    ]
