# Generated by Django 5.0 on 2025-10-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradebook',
            options={'verbose_name': 'gradebook entry', 'verbose_name_plural': 'gradebook entries'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['-created_at'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['quiz', 'position'], 'verbose_name': 'quiz question', 'verbose_name_plural': 'quiz questions'},
        ),
        migrations.RemoveIndex(
            model_name='questionbank',
            name='assessments_course__d617aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionbank',
            name='assessments_is_acti_5cd00b_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='assessments_course__aae811_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='assessments_quiz_id_6c0e5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='assessments_status_ddb9e1_idx',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='last_calculated',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_correct_answers_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed file extensions, e.g., [".pdf", ".docx"]', verbose_name='allowed file types'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz/Test'), ('FILE_UPLOAD', 'File Upload'), ('TEXT', 'Text Submission'), ('CODE', 'Code Submission'), ('URL', 'URL/Link Submission'), ('MANUAL_GRADE', 'Manual Grade Only'), ('EXTERNAL', 'External Tool')], default='FILE_UPLOAD', max_length=20, verbose_name='assignment type'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='auto_grading_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic grading for code submissions', verbose_name='auto grading enabled'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='external_tool_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='external tool config'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='external_tool_url',
            field=models.URLField(blank=True, null=True, verbose_name='external tool URL'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade_anonymously',
            field=models.BooleanField(default=False, verbose_name='grade anonymously'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_file_size',
            field=models.IntegerField(default=10485760, help_text='Maximum file size in bytes', verbose_name='max file size'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_files',
            field=models.IntegerField(default=5, help_text='Maximum number of files allowed', verbose_name='max files'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='peer_review_enabled',
            field=models.BooleanField(default=False, verbose_name='peer review enabled'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='peer_reviews_required',
            field=models.IntegerField(default=0, verbose_name='peer reviews required'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='programming_language',
            field=models.CharField(blank=True, help_text='For code submissions: python, java, cpp, etc.', max_length=50, verbose_name='programming language'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='assessments.quiz'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='Test cases for auto-grading code', verbose_name='test cases'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='override_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='override grade'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='override_reason',
            field=models.TextField(blank=True, verbose_name='override reason'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(default=1, verbose_name='attempts allowed'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='pass percentage'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers_at',
            field=models.DateTimeField(blank=True, help_text='When to show correct answers to students', null=True, verbose_name='show correct answers at'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True, verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, verbose_name='letter grade'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCHING', 'Matching'), ('NUMERICAL', 'Numerical'), ('FORMULA', 'Formula'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay'), ('CODE', 'Code Question')], max_length=30, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='attempt number'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='points_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the default points for this question in this quiz', max_digits=6, null=True, verbose_name='points override'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_associations', to='assessments.questionbank'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_type'], name='assessments_assignm_b0bd4d_idx'),
        ),
    ]
