# Generated by Django 5.0 on 2025-10-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_gradebook_unique_together_and_more'),
        ('courses', '0002_initial'),
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Gradebook category for weighting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='gradebook.gradebookcategory'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module this assignment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.module'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.DeleteModel(
            name='Gradebook',
        ),
    ]
