# Generated by Django 5.0 on 2025-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='department ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='enrollment status'),
        ),
    ]
