# Generated by Django 5.0 on 2025-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plagiarism_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='plagiarism score'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_count',
            field=models.IntegerField(default=1, verbose_name='submission count'),
        ),
    ]
