# Generated by Django 5.0 on 2025-10-17 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_students', models.IntegerField(default=0, verbose_name='total students')),
                ('active_students', models.IntegerField(default=0, verbose_name='active students')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='average grade')),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='completion rate')),
                ('total_submissions', models.IntegerField(default=0, verbose_name='total submissions')),
                ('total_quiz_attempts', models.IntegerField(default=0, verbose_name='total quiz attempts')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculated at')),
            ],
            options={
                'verbose_name': 'course analytics',
                'verbose_name_plural': 'course analytics',
            },
        ),
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('times_answered', models.IntegerField(default=0, verbose_name='times answered')),
                ('times_correct', models.IntegerField(default=0, verbose_name='times correct')),
                ('times_incorrect', models.IntegerField(default=0, verbose_name='times incorrect')),
                ('correct_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='correct rate')),
                ('difficulty_index', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='difficulty index')),
                ('discrimination_index', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='discrimination index')),
                ('average_time_seconds', models.IntegerField(blank=True, null=True, verbose_name='average time (seconds)')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
            ],
            options={
                'verbose_name': 'question statistics',
                'verbose_name_plural': 'question statistics',
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('VIEW_COURSE', 'View Course'), ('VIEW_MODULE', 'View Module'), ('VIEW_RESOURCE', 'View Resource'), ('SUBMIT_ASSIGNMENT', 'Submit Assignment'), ('START_QUIZ', 'Start Quiz'), ('SUBMIT_QUIZ', 'Submit Quiz'), ('VIEW_GRADE', 'View Grade')], max_length=50, verbose_name='activity type')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='object type')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='object ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'student activity',
                'verbose_name_plural': 'student activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
