global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'lms-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lms-user-service:8081', 'lms-course-service:8082', 'lms-assessment-service:8083', 'lms-api-gateway:8080']

