# Generated by Django 5.0 on 2025-10-19 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_alter_gradebook_unique_together_and_more'),
        ('courses', '0002_initial'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Points earned', max_digits=6, null=True, verbose_name='score')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible points', max_digits=6, verbose_name='max score')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Score as percentage', max_digits=5, null=True, verbose_name='percentage')),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('EXCUSED', 'Excused'), ('MISSING', 'Missing'), ('LATE', 'Late')], default='NOT_SUBMITTED', max_length=20, verbose_name='status')),
                ('is_late', models.BooleanField(default=False, verbose_name='late submission')),
                ('is_excused', models.BooleanField(default=False, verbose_name='excused')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('override_score', models.DecimalField(blank=True, decimal_places=2, help_text='Manual override of calculated score', max_digits=6, null=True, verbose_name='override score')),
                ('override_at', models.DateTimeField(blank=True, null=True, verbose_name='override at')),
                ('override_reason', models.TextField(blank=True, verbose_name='override reason')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='assessments.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='courses.course')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_overrides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gradebook_entry', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'gradebook entry',
                'verbose_name_plural': 'gradebook entries',
                'ordering': ['course', 'student', 'assignment'],
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='old score')),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='new score')),
                ('change_reason', models.TextField(blank=True, verbose_name='change reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
                ('gradebook_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gradebook.gradebookentry')),
            ],
            options={
                'verbose_name': 'grade history',
                'verbose_name_plural': 'grade histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseGradeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total points earned')),
                ('total_points_possible', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total points possible')),
                ('current_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Current percentage grade', max_digits=5, null=True, verbose_name='current grade')),
                ('letter_grade', models.CharField(blank=True, help_text='A, B, C, D, F, etc.', max_length=5, verbose_name='letter grade')),
                ('category_grades', models.JSONField(blank=True, default=dict, help_text='Grades broken down by category', verbose_name='category grades')),
                ('assignments_completed', models.IntegerField(default=0, verbose_name='assignments completed')),
                ('assignments_total', models.IntegerField(default=0, verbose_name='assignments total')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='final grade')),
                ('is_final', models.BooleanField(default=False, verbose_name='is final')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course grade summary',
                'verbose_name_plural': 'course grade summaries',
                'ordering': ['course', 'student'],
                'indexes': [models.Index(fields=['course', 'student'], name='gradebook_c_course__06db4a_idx'), models.Index(fields=['current_grade'], name='gradebook_c_current_057973_idx')],
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GradebookCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight percentage (e.g., 30 for 30%)', max_digits=5, verbose_name='weight')),
                ('drop_lowest', models.IntegerField(default=0, help_text='Number of lowest scores to drop', verbose_name='drop lowest')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_categories', to='courses.course')),
            ],
            options={
                'verbose_name': 'gradebook category',
                'verbose_name_plural': 'gradebook categories',
                'ordering': ['course', 'position'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='gradebookentry',
            index=models.Index(fields=['course', 'student'], name='gradebook_g_course__75e3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebookentry',
            index=models.Index(fields=['assignment'], name='gradebook_g_assignm_3024c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebookentry',
            index=models.Index(fields=['status'], name='gradebook_g_status_62a69a_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebookentry',
            index=models.Index(fields=['graded_at'], name='gradebook_g_graded__81af7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradebookentry',
            unique_together={('course', 'student', 'assignment')},
        ),
    ]
