# Generated by Django 5.0 on 2025-10-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradebookentry',
            options={'ordering': ['course', 'student'], 'verbose_name': 'gradebook entry', 'verbose_name_plural': 'gradebook entries'},
        ),
        migrations.RemoveIndex(
            model_name='gradebookentry',
            name='gradebook_g_assignm_3024c6_idx',
        ),
    ]
