# Generated by Django 5.0 on 2025-10-17 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='course code')),
                ('title_uk', models.CharField(max_length=255, verbose_name='title (Ukrainian)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='title (English)')),
                ('description_uk', models.TextField(blank=True, verbose_name='description (Ukrainian)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('syllabus', models.TextField(blank=True, verbose_name='syllabus')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20, verbose_name='visibility')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='thumbnail')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('max_students', models.IntegerField(blank=True, null=True, verbose_name='max students')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_course', models.CharField(choices=[('TEACHER', 'Teacher'), ('TA', 'Teaching Assistant'), ('STUDENT', 'Student')], max_length=20, verbose_name='role in course')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='final grade')),
            ],
            options={
                'verbose_name': 'course member',
                'verbose_name_plural': 'course members',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('content_meta', models.JSONField(blank=True, default=dict, verbose_name='content metadata')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['course', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF Document'), ('SLIDE', 'Presentation'), ('LINK', 'External Link'), ('TEXT', 'Text Content'), ('CODE', 'Code File'), ('OTHER', 'Other')], max_length=20, verbose_name='resource type')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_resources/', verbose_name='file')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='external URL')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='storage path')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='downloadable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['module', 'position'],
            },
        ),
    ]
