# Generated by Django 5.0 on 2025-10-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['user', 'course'], name='analytics_s_user_id_cff824_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['activity_type'], name='analytics_s_activit_da9bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['created_at'], name='analytics_s_created_9e42a9_idx'),
        ),
    ]
